<a href="https://colab.research.google.com/github/adi200477/DEEP-VISION-AI-Workshop/blob/main/Day_2_Numpy_Practical_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
# 1
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# 2
print(arr[:, 0])

[1 4 7]


In [9]:
# 3
print(arr[2, :])

[7 8 9]


In [10]:
# 4
print(arr[1,1])

5


In [11]:
# 5
print(arr[1,0])

4


In [12]:
# 6
print(arr.diagonal())

[1 5 9]


In [45]:
# 7
print(arr[::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [47]:
# 8
arr[arr % 2 == 0] = 0
print(arr)

[[1 0 3]
 [0 5 0]
 [7 0 9]]


In [17]:
# 9
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(3, 3)
9
2
int64


In [20]:
# 10
print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.max())


45
5.0
1
9


In [30]:
# 11
arr1 = np.arange(1,25)
print("Orginal Array")
print(arr1,"\n")
print("Reshaped (6, 4)")
print(arr1.reshape(6,4),"\n")
print("Reshaped (2, 3, 4)")
print(arr1.reshape(2, 3, 4),"\n")

Orginal Array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 

Reshaped (6, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]] 

Reshaped (2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] 



In [71]:
# 12
arr2 = np.random.randint(25, 100, 20)
print(arr2, "\n")
print("Mean")
print(np.mean(arr2), "\n")
print("Median")
print(np.median(arr2), "\n")
print("Standard Deviation")
print(np.std(arr2), "\n")

[68 69 51 65 92 66 62 83 48 27 93 74 59 90 66 27 33 29 87 99] 

Mean
64.4 

Median
66.0 

Standard Deviation
22.294393914165955 



In [63]:
# 13
print(arr2[arr2>50])

[76 80 61 66 98 93 79 97 71 86 62 92]


In [64]:
# 14
arr2[arr2 < 50 ] = 50
print(arr2)



[50 50 76 50 80 61 50 66 98 50 50 50 50 93 79 97 71 86 62 92]


In [70]:
# 15
arr3 = np.array([[2, 5, 8], [9, 3, 6], [1, 4, 7]])
print("First Matrix")
print(arr, "\n")
print("Second Matrix")
print(arr3, "\n")
print("Addition")
print(arr + arr3, "\n")
print("Substraction")
print(arr - arr3, "\n")
print("Multiplication")
print(arr * arr3, "\n")
print("Transpose of first matrix")
print(arr.transpose(), "\n")
print("Transpose of second matrix")
print(arr3.transpose(), "\n")

First Matrix
[[1 0 3]
 [0 5 0]
 [7 0 9]] 

Second Matrix
[[2 5 8]
 [9 3 6]
 [1 4 7]] 

Addition
[[ 3  5 11]
 [ 9  8  6]
 [ 8  4 16]] 

Substraction
[[-1 -5 -5]
 [-9  2 -6]
 [ 6 -4  2]] 

Multiplication
[[ 2  0 24]
 [ 0 15  0]
 [ 7  0 63]] 

Transpose of first matrix
[[1 0 7]
 [0 5 0]
 [3 0 9]] 

Transpose of second matrix
[[2 9 1]
 [5 3 4]
 [8 6 7]] 

